### ISSUE TITLE
ERROR: AddressSanitizer: SEGV on unknown address in stb_image.c::get8()

### ISSUE THREAD

**Issue by EnchantedJohn** [ARM-software/astc-encoder#22]
Hello.guys! I use my fuzzing tools. I found a Segmentation fault. I want to show my error information.

I have use ASAN. There is the error informaiton:

```
Encoding settings:

2D Block size: 6x6 (3.56 bpp)
3D Block size: 6x6x1 (3.56 bpp)
Radius for mean-and-stdev calculations: 0 texels
RGB power: 1
RGB base-weight: 1
RGB local-mean weight: 0
RGB local-stdev weight: 0
RGB mean-and-stdev mixing across color channels: 0
Alpha power: 1
Alpha base-weight: 1
Alpha local-mean weight: 0
Alpha local-stdev weight: 0
RGB weights scale with alpha: disabled
Color channel relative weighting: R=1 G=1 B=1 A=1
Block-artifact suppression parameter : 0
Number of distinct partitionings to test: 25 (preset)
PSNR decibel limit: 2D: 40.529411 3D: 40.529411 (preset)
1->2 partition limit: 1.200000
Dual-plane color-correlation cutoff: 0.750000 (preset)
Block Mode Percentile Cutoff: 75.000000 (preset)
Max refinement iterations: 2 (preset)
Thread count : 64 (autodetected)

ASAN:SIGSEGV
=================================================================
==206812==ERROR: AddressSanitizer: SEGV on unknown address 0x7ffdbfd918b4 (pc 0x0000005a7db7 sp 0x7ffdd7d5fe70 bp 0x7ffdbfd918b4 T0)
    #0 0x5a7db6 in get8 /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:732
    #1 0x5a7db6 in get16 /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:796
    #2 0x5a7db6 in get32 /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:802
    #3 0x5d66b7 in parse_png_file /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:2826
    #4 0x5eb086 in do_png /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:2834
    #5 0x5eb086 in stbi_png_load /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:2857
    #6 0x5eb086 in stbi_load_main /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:537
    #7 0x60757a in stbi_load_from_file /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:571
    #8 0x60757a in stbi_load /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:562
    #9 0x536f14 in load_image_with_stb(char const*, int, int*) /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/astc_stb_tga.cpp:66
    #10 0x4ed8ad in astc_codec_load_image(char const*, int, int*) /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/astc_image_load_store.cpp:1328
    #11 0x404408 in main /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/astc_toplevel.cpp:2329
    #12 0x7f88f515ef44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21f44)
    #13 0x40a7dc (/home/lx/5_18/astc/ASAN/astc-encoder-master/Source/astcenc+0x40a7dc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/lx/5_18/astc/ASAN/astc-encoder-master/Source/stb_image.c:732 get8
==206812==ABORTING
```

Then there is GDB information:

```
(gdb) bt
#0  0x00000000004580b3 in get32(stbi*) ()
#1  0x000000000045ea8c in parse_png_file(png*, int, int) ()
#2  0x0000000000461542 in stbi_load_main(stbi*, int*, int*, int*, int) ()
#3  0x0000000000464988 in stbi_load ()
#4  0x0000000000441d55 in load_image_with_stb(char const*, int, int*) ()
#5  0x00000000004313b6 in astc_codec_load_image(char const*, int, int*) ()
#6  0x0000000000401f10 in main ()
```

```
(gdb) x/8i $pc
=> 0x4580b3 <_ZL5get32P4stbi+387>:	movzbl (%rax),%ebp
   0x4580b6 <_ZL5get32P4stbi+390>:	shl    $0x8,%ebp
   0x4580b9 <_ZL5get32P4stbi+393>:	cmp    %r8,%rcx
   0x4580bc <_ZL5get32P4stbi+396>:	jae    0x457fbc <_ZL5get32P4stbi+140>
   0x4580c2 <_ZL5get32P4stbi+402>:	lea    0x1(%rcx),%rdi
   0x4580c6 <_ZL5get32P4stbi+406>:	mov    %rdi,0xb8(%rbx)
   0x4580cd <_ZL5get32P4stbi+413>:	movzbl (%rcx),%eax
   0x4580d0 <_ZL5get32P4stbi+416>:	add    %eax,%ebp
```

```
(gdb) i r
rax            0x7fffec5b0fce	140737158778830
rbx            0x7fffffffd650	140737488344656
rcx            0x7fffec5b0fcf	140737158778831
rdx            0x74	116
rsi            0x7fffffffd688	140737488344712
rdi            0x7fffffffd650	140737488344656
rbp            0xffffffffec5b393a	0xffffffffec5b393a
rsp            0x7fffffffbfb0	0x7fffffffbfb0
r8             0x7fffffffd708	140737488344840
r9             0xfdf7a67adda06d4e	-146465416231752370
r10            0xc9e005181b084210	-3900111676211969520
r11            0x968	2408
r12            0xb5c196af	3049363119
r13            0x2945	10565
r14            0x7fffffffd650	140737488344656
r15            0x7fffffffd5e0	140737488344544
rip            0x4580b3	0x4580b3 <get32(stbi*)+387>
eflags         0x10287	[ CF PF SF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
```

**Comment by EnchantedJohn** [comment]
I think it is caused by get8().Maybe It is Out of bounds. When it execute this statement ( return *s->img_buffer++;)

the code is :

```
stbi_inline static int get8(stbi *s)
{
   if (s->img_buffer < s->img_buffer_end)
      return *s->img_buffer++;
   if (s->read_from_callbacks) {
      refill_buffer(s);
      return *s->img_buffer++;
   }
   return 0;
}
```

**Comment by solidpixel** [comment]
No means to reproduce this specific issue without the test file to verify that this is fixed, but the upgrade to the new stb_image library in PR #48 solves many cases of corrupt images causing problems.
