### ISSUE TITLE
Segmentation fault in get16(stbi*) ()

### ISSUE THREAD

**Issue by EnchantedJohn** [ARM-software/astc-encoder#29]
Hello,everyone! I use my company tools to fuzz astc.I found a crash in astc on Linux64.So I will show you some detail information to help you find the leak.

**Comment by EnchantedJohn** [comment]
so I use the command is 
/home/lx/coverage/testapp/astc/HFL/astcenc -c xxx.png test.astc 6x6 -medium

then there is gdb information:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000455493 in get16(stbi*) ()
(gdb) bt
#0  0x0000000000455493 in get16(stbi*) ()
#1  0x000000000045d964 in parse_png_file(png*, int, int) ()
#2  0x000000000045fbea in stbi_load_main(stbi*, int*, int*, int*, int) ()
#3  0x0000000000463008 in stbi_load ()
#4  0x000000000044228d in load_image_with_stb(char const*, int, int*) ()
#5  0x00000000004314fd in astc_codec_load_image(char const*, int, int*) ()
#6  0x00000000004022e4 in main ()
(gdb) i r
rax            0x7fffb2b28796	140736191432598
rbx            0x7fffffffd450	140737488344144
rcx            0x7fffb2b28797	140736191432599
rdx            0x7fffffffd508	140737488344328
rsi            0x7fffffffd508	140737488344328
rdi            0x7fffffffd450	140737488344144
rbp            0x0	0x0
rsp            0x7fffffffbe90	0x7fffffffbe90
r8             0x3	3
r9             0xb2b2b2b2b2b2b2b2	-5570193308531903822
r10            0xb2b2b2b2b2b2b2b2	-5570193308531903822
r11            0x246	582
r12            0x0	0
r13            0xffffffffb2b2b2b2	-1296911694
r14            0xb2b20000	2998009856
r15            0x7fffffffd450	140737488344144
rip            0x455493	0x455493 <get16(stbi*)+195>
eflags         0x10297	[ CF PF AF SF IF RF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) x/10i $pc
=> 0x455493 <_ZL5get16P4stbi+195>:	movzbl (%rax),%ebp
   0x455496 <_ZL5get16P4stbi+198>:	shl    $0x8,%ebp
   0x455499 <_ZL5get16P4stbi+201>:	cmp    %rdx,%rcx
   0x45549c <_ZL5get16P4stbi+204>:	jae    0x455440 <_ZL5get16P4stbi+112>
   0x45549e <_ZL5get16P4stbi+206>:	lea    0x1(%rcx),%rax
   0x4554a2 <_ZL5get16P4stbi+210>:	mov    %rax,0xb8(%rbx)
   0x4554a9 <_ZL5get16P4stbi+217>:	movzbl (%rcx),%eax
   0x4554ac <_ZL5get16P4stbi+220>:	pop    %rbx
   0x4554ad <_ZL5get16P4stbi+221>:	add    %ebp,%eax
   0x4554af <_ZL5get16P4stbi+223>:	pop    %rbp
```

**Comment by solidpixel** [comment]
No means to reproduce this specific issue without the test file to verify that this is fixed, but the upgrade to the new stb_image library in PR #48 solves many cases of corrupt images causing problems.
