### ISSUE TITLE
astc Aborted in __GI_raise()

### ISSUE THREAD

**Issue by EnchantedJohn** [ARM-software/astc-encoder#30]
Hello,everyone! I use my company tools to fuzz astc.I found a abort in astc on Linux64. I think it is due to zbuild_huffman().So I will show you some detail information to help you find the leak.

**Comment by EnchantedJohn** [comment]
so I use the command is
/home/lx/coverage/testapp/astc/HFL/astcenc -c xxx.png test.astc 6x6 -medium

then there is gdb information:

```
Program received signal SIGABRT, Aborted.
0x00007ffff720dc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff720dc37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff7211028 in __GI_abort () at abort.c:89
#2  0x00007ffff7206bf6 in __assert_fail_base (fmt=0x7ffff735b058 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x4c08fe "sizes[i] <= (1 << i)", file=file@entry=0x4c0871 "stb_image.c", 
    line=line@entry=1996, function=function@entry=0x4c10e0 <zbuild_huffman(zhuffman*, unsigned char*, int)::__PRETTY_FUNCTION__> "int zbuild_huffman(zhuffman*, uint8*, int)") at assert.c:92
#3  0x00007ffff7206ca2 in __GI___assert_fail (assertion=0x4c08fe "sizes[i] <= (1 << i)", file=0x4c0871 "stb_image.c", line=1996, 
    function=0x4c10e0 <zbuild_huffman(zhuffman*, unsigned char*, int)::__PRETTY_FUNCTION__> "int zbuild_huffman(zhuffman*, uint8*, int)") at assert.c:101
#4  0x00000000004551db in zbuild_huffman(zhuffman*, unsigned char*, int) ()
#5  0x000000000045c3ba in compute_huffman_codes(zbuf*) ()
#6  0x000000000045c933 in parse_zlib(zbuf*, int) ()
#7  0x000000000045deda in parse_png_file(png*, int, int) ()
#8  0x000000000045fbea in stbi_load_main(stbi*, int*, int*, int*, int) ()
#9  0x0000000000463008 in stbi_load ()
#10 0x000000000044228d in load_image_with_stb(char const*, int, int*) ()
#11 0x00000000004314fd in astc_codec_load_image(char const*, int, int*) ()
#12 0x00000000004022e4 in main ()
(gdb) i r
rax            0x0	0
rbx            0x7ffff7ff5000	140737354092544
rcx            0x7ffff720dc37	140737339513911
rdx            0x6	6
rsi            0x18826	100390
rdi            0x18826	100390
rbp            0x7ffff735b058	0x7ffff735b058
rsp            0x7fffffffb078	0x7fffffffb078
r8             0xfefefefefefefe00	-72340172838076928
r9             0x6fe070	7331952
r10            0x8	8
r11            0x202	514
r12            0x4c08fe	4983038
r13            0x4c10e0	4985056
r14            0x12a	298
r15            0x3	3
rip            0x7ffff720dc37	0x7ffff720dc37 <__GI_raise+55>
eflags         0x202	[ IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) x/10i $pc
=> 0x7ffff720dc37 <__GI_raise+55>:	cmp    $0xfffffffffffff000,%rax
   0x7ffff720dc3d <__GI_raise+61>:	ja     0x7ffff720dc5d <__GI_raise+93>
   0x7ffff720dc3f <__GI_raise+63>:	repz retq 
   0x7ffff720dc41 <__GI_raise+65>:	nopl   0x0(%rax)
   0x7ffff720dc48 <__GI_raise+72>:	test   %ecx,%ecx
   0x7ffff720dc4a <__GI_raise+74>:	jg     0x7ffff720dc27 <__GI_raise+39>
   0x7ffff720dc4c <__GI_raise+76>:	mov    %ecx,%eax
   0x7ffff720dc4e <__GI_raise+78>:	neg    %eax
   0x7ffff720dc50 <__GI_raise+80>:	and    $0x7fffffff,%ecx
   0x7ffff720dc56 <__GI_raise+86>:	cmove  %esi,%eax
```

**Comment by solidpixel** [comment]
This isn't an unconstrained crash; the code explicitly includes an assertion so this is a managed exit without any security implications, even though it's not a "pretty" exit.

P.S. Thanks, for raising these, but it would be really helpful if you actually linked the input image files which caused the problem, it would make reproducing the issue a lot faster.
