### ISSUE TITLE
Detected Memory Leaks

### ISSUE THREAD

**Issue by p870613** [ARM-software/astc-encoder#303]
# Version
```
astcenc v3.3.0, 64-bit sse2
```
# Environment
```
➜  Source g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

➜  Source lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
➜  Source uname -a
Linux lin-System-Product-Name 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
# Command
- update `CMakeLists.txt`
```
set(CMAKE_BUILD_TYPE "Debug")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
set(CMAKE_LINKER_FLAGS_DEBUG "${CMAKE_LINKER_FLAGS_DEBUG} -fno-omit-frame-pointer -fsanitize=address")
```

- compile command
```
cmake .
make
```

# Result
The result of running without ASAN:
```
➜  Source ./astcenc-native -cl dd ./out.astc 6x6 -fast
ERROR: Failed to load image dd (can't fopen)
ERROR: Failed to load uncompressed image file
```

Information obtained by using ASAN:
```
➜  Source ./astcenc-native -cl dd ./out.astc 6x6 -fast
ERROR: Failed to load image dd (can't fopen)
ERROR: Failed to load uncompressed image file

=================================================================
==1285837==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 1488 byte(s) in 1 object(s) allocated from:
    #0 0x7eff6360d947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x55a871ff2088 in astcenc_context_alloc(astcenc_config const*, unsigned int, astcenc_context**) /home/lin/astc-encoder-3.3/Source/astcenc_entry.cpp:753
    #2 0x55a871fe7b4d in main /home/lin/astc-encoder-3.3/Source/astcenccli_toplevel.cpp:1536
    #3 0x7eff62fe70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 16736768 byte(s) in 1 object(s) allocated from:
    #0 0x7eff6360caa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
    #1 0x55a8720036cf in compression_working_buffers* aligned_malloc<compression_working_buffers>(unsigned long, unsigned long) (/home/lin/astc-encoder-3.3/Source/astcenc-native+0x13f6cf)
    #2 0x55a871ff67d2 in astcenc_context_alloc(astcenc_config const*, unsigned int, astcenc_context**) /home/lin/astc-encoder-3.3/Source/astcenc_entry.cpp:795
    #3 0x55a871fe7b4d in main /home/lin/astc-encoder-3.3/Source/astcenccli_toplevel.cpp:1536
    #4 0x7eff62fe70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 4212864 byte(s) in 12 object(s) allocated from:
    #0 0x7eff6360caa5 in posix_memalign (/lib/x86_64-linux-gnu/libasan.so.5+0x10eaa5)
    #1 0x55a872031237 in decimation_info* aligned_malloc<decimation_info>(unsigned long, unsigned long) /home/lin/astc-encoder-3.3/Source/astcenc_internal.h:2341
    #2 0x55a87202e9eb in construct_dt_entry_2d /home/lin/astc-encoder-3.3/Source/astcenc_block_sizes.cpp:774
    #3 0x55a87202f350 in construct_block_size_descriptor_2d /home/lin/astc-encoder-3.3/Source/astcenc_block_sizes.cpp:910
    #4 0x55a872031056 in init_block_size_descriptor(unsigned int, unsigned int, unsigned int, bool, float, block_size_descriptor&) /home/lin/astc-encoder-3.3/Source/astcenc_block_sizes.cpp:1132
    #5 0x55a871ff2566 in astcenc_context_alloc(astcenc_config const*, unsigned int, astcenc_context**) /home/lin/astc-encoder-3.3/Source/astcenc_entry.cpp:773
    #6 0x55a871fe7b4d in main /home/lin/astc-encoder-3.3/Source/astcenccli_toplevel.cpp:1536
    #7 0x7eff62fe70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

Indirect leak of 3459192 byte(s) in 1 object(s) allocated from:
    #0 0x7eff6360d947 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.5+0x10f947)
    #1 0x55a871ff2398 in astcenc_context_alloc(astcenc_config const*, unsigned int, astcenc_context**) /home/lin/astc-encoder-3.3/Source/astcenc_entry.cpp:771
    #2 0x55a871fe7b4d in main /home/lin/astc-encoder-3.3/Source/astcenccli_toplevel.cpp:1536
    #3 0x7eff62fe70b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)

SUMMARY: AddressSanitizer: 24410312 byte(s) leaked in 15 allocation(s).

```
Thanks !!

**Comment by solidpixel** [comment]
Not a bug; the command line wrapper knowingly uses process exit to free resources. Closed.
